# Generated by Django 5.1.7 on 2025-03-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="code",
            field=models.IntegerField(
                blank=True, max_length=4, null=True, verbose_name="Код подтверждения"
            ),
        ),
    ]
