# Generated by Django 5.1.7 on 2025-03-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_is_subscribed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="code",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Код подтверждения"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_subscribed",
            field=models.BooleanField(default=False, verbose_name="Подписка"),
        ),
    ]
