# Generated by Django 5.1.7 on 2025-03-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(verbose_name="Текст записи"),
        ),
    ]
