# Generated by Django 5.1.7 on 2025-03-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0003_alter_post_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(
                blank=True,
                choices=[
                    ("мир", "Мир"),
                    ("страны", "Страны"),
                    ("технология", "Технология"),
                    ("одежда", "Одежда"),
                    ("культура", "Культура"),
                    ("бизнес", "Бизнес"),
                    ("политика", "Политика"),
                    ("мнение", "Мнение"),
                    ("наука", "Наука"),
                    ("здоровье", "Здоровье"),
                    ("стиль", "Стиль"),
                    ("путешествие", "Путешествие"),
                ],
                max_length=100,
                null=True,
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="views_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Счётчик просмотров"
            ),
        ),
    ]
