# Generated by Django 5.1.7 on 2025-03-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0005_alter_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/images/",
                verbose_name="Изображение",
            ),
        ),
    ]
