# Generated by Django 5.1.7 on 2025-03-28 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0006_alter_post_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="user_likes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Лайки",
            ),
        ),
    ]
