# Generated by Django 5.1.7 on 2025-03-28 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0007_post_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
    ]
